select * from customer limit 20

SELECT column_name
FROM information_schema.columns
WHERE table_name = 'customer';


Q1. What is the total revenue generated by male vs. female customers?
SELECT "gender",
       SUM("purchase_amount") AS revenue
FROM customer
GROUP BY "gender";

Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, Round(AVG(review_rating::numeric),1) as "Avarage Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

Q4. Compare the average purchase amounts between Standard and Express Shipping.
SELECT shipping_type,
round(AVG("purchase_amount"),2)
FROM customer
where shipping_type in ('Standard','Express')
GROUP BY shipping_type;

Q5. Do subscribed customers spend more?
Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,
count (customer_id) as total_customer,
round(avg("purchase_amount"),2) as avg_spend,
round(sum("purchase_amount"),2) as total_revenew
from customer
group by subscription_status
order by total_revenew,avg_spend  desc; 


Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
round(100*AVG(case when discount_applied = 'Yes' then 1 else 0 end), 2 ) as total_discount
from customer
group by item_purchased
order by total_discount desc
limit 5;
Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and analyze their spending behavior.

with customer_type as (
select customer_id,previous_purchases,
case 
  when previous_purchases = 1 then 'New'
  when previous_purchases between 2 and 10 then 'Returning'
  else 'Loyal'
  end as customer_segment
  from customer
)
select customer_segment, count(*) as "Number of customer"
from customer_type
group by customer_segment

Q8. What are the top 3 most purchased products within each category?

WITH item_count AS (
    SELECT category,
           item_purchased,
           COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(*) DESC
           ) AS item_ranked
    FROM customer
    GROUP BY category, item_purchased
)
SELECT *
FROM item_count;

-- Q9: Are customers who are repeat buyers 
-- (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyer
from customer
where previous_purchases>5
group by subscription_status


Q10. What is the revenue contribution by each age group?

select age_grp,
sum (purchase_amount) as total_revenew
from customer
group by age_grp
order by total_revenew desc

